---
title: "Lab 1"
author: "Ruoyu Wang"
date: "2020/1/9"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(tidyverse)
library(janitor)
library(kableExtra)
```

Read in naa_fistheris.csv data

```{r}
us_landings <- readr::read_csv(here::here("data", "noaa_fisheries.csv")) 
```

now make a tidy version of data frame
```{r}
landings_tidy <- us_landings %>% 
  janitor::clean_names() %>% 
  # change the character in lower case
  mutate(state = str_to_lower(state),
         afs_name = str_to_lower(afs_name),
         dollars_num = parse_number(dollars_usd))
```

let's just get some information for salmon:

```{r}
salmon_landings <- landings_tidy %>% 
  mutate(afs_clean = str_remove(afs_name, pattern = "aggregate")) %>% 
  filter(str_detect(afs_clean, pattern = "salmon")) %>% 
  separate(afs_clean, into = c("group", "species"), sep = ",")
```

Find some grouped summary data:

Find annual total US landings and dollar value (annual ACROSS ALL STATES) for each type of salmon using "group_by" and "summarize())"

```{r}
salmon_summary <- salmon_landings %>% 
  group_by(year, species) %>% 
  summarize(
    tot_landings = sum(landings_pounds, na.rm = TRUE),
    tot_value = sum(dollars_num)
  )
```

Make a graph

```{r}
salmon_landings_graph <- ggplot(data = salmon_summary, 
                                aes(x = year, y = tot_landings, group = species)) +
  geom_line(aes(color = species))+
  theme_minimal()

salmon_landings_graph
```

Now we 'll export our graph with ggsave:

```{r}
ggsave(plot = salmon_landings_graph, 
       here::here("figures", "us_salmon_ry.png"),
       height = 5,
       width = 8,
       dpi = 400)
```


Make a nice kable table:

```{r}
salmon_first_5 <- salmon_summary %>% 
  head(5)
```

use kable
```{r}
kable(salmon_first_5) %>% 
  kable_styling(bootstrap_options = "striped",
                full_width = FALSE)
```

